#!/bin/bash
PROJECT_NAME=test_activation_functions
./${PROJECT_NAME} --Logistic1         
./${PROJECT_NAME} --Logistic2         
./${PROJECT_NAME} --Logistic3         
./${PROJECT_NAME} --Logistic4         
./${PROJECT_NAME} --InverseTangent1   
./${PROJECT_NAME} --InverseTangent2   
./${PROJECT_NAME} --InverseTangent3   
./${PROJECT_NAME} --InverseTangent4   
./${PROJECT_NAME} --HyperbolicTangent1
./${PROJECT_NAME} --HyperbolicTangent2
./${PROJECT_NAME} --HyperbolicTangent3
./${PROJECT_NAME} --HyperbolicTangent4
./${PROJECT_NAME} --Algebraic1        
./${PROJECT_NAME} --Algebraic2        
./${PROJECT_NAME} --Algebraic3        
./${PROJECT_NAME} --Algebraic4        
./${PROJECT_NAME} --Erf1              
./${PROJECT_NAME} --Erf2              
./${PROJECT_NAME} --Erf3              
./${PROJECT_NAME} --Erf4              
./${PROJECT_NAME} --Gompertz1         
./${PROJECT_NAME} --Gompertz2         
./${PROJECT_NAME} --Gompertz3         
./${PROJECT_NAME} --Gompertz4         
./${PROJECT_NAME} --Control1          
./${PROJECT_NAME} --Control2          
./${PROJECT_NAME} --Control3          
./${PROJECT_NAME} --Control4          
