#!/bin/bash
PROJECT_NAME=test_matrix_template
./${PROJECT_NAME} --MulConstMatrix        $1
./${PROJECT_NAME} --Ostream               $1
./${PROJECT_NAME} --Transpose             $1
./${PROJECT_NAME} --Sigmoid               $1
./${PROJECT_NAME} --DSigmoid              $1
./${PROJECT_NAME} --Err                   $1
./${PROJECT_NAME} --Comp                  $1
./${PROJECT_NAME} --Kro                   $1
./${PROJECT_NAME} --Dot                   $1
./${PROJECT_NAME} --Sum                   $1
./${PROJECT_NAME} --Constructor1          $1
./${PROJECT_NAME} --Constructor2          $1
./${PROJECT_NAME} --Constructor3          $1
./${PROJECT_NAME} --Fill1                 $1
./${PROJECT_NAME} --Fill2                 $1
./${PROJECT_NAME} --Fill3                 $1
./${PROJECT_NAME} --PutMatrix             $1
./${PROJECT_NAME} --GetMatrix             $1
./${PROJECT_NAME} --GetRows               $1
./${PROJECT_NAME} --GetColumns            $1
./${PROJECT_NAME} --Size                  $1
./${PROJECT_NAME} --At                    $1
./${PROJECT_NAME} --Addition              $1
./${PROJECT_NAME} --Subtraction           $1
./${PROJECT_NAME} --Multiplication        $1
./${PROJECT_NAME} --Assignment            $1
./${PROJECT_NAME} --AdditionAssignment    $1
./${PROJECT_NAME} --SubtractionAssignment $1
