#!/bin/bash
PROJECT_NAME=test_neural_network
./${PROJECT_NAME} --N32_Ostream                                          
./${PROJECT_NAME} --N32_CheckDim                                         
./${PROJECT_NAME} --N32_Constructor1                                     
./${PROJECT_NAME} --N32_Constructor2                                     
./${PROJECT_NAME} --N32_Constructor3                                     
./${PROJECT_NAME} --N32_GetRows                                          
./${PROJECT_NAME} --N32_GetColumns                                       
./${PROJECT_NAME} --N32_SetNext                                          
./${PROJECT_NAME} --N32_SetPrevious                                      
./${PROJECT_NAME} --N32_SetLearningRate                                  
./${PROJECT_NAME} --N32_PutNeural                                        
./${PROJECT_NAME} --N32_Propagate1                                       
./${PROJECT_NAME} --N32_Propagate2                                       
./${PROJECT_NAME} --N32_BackPropagate1                                   
./${PROJECT_NAME} --N32_BackPropagate2                                   
./${PROJECT_NAME} --NMS_Ostream                                          
./${PROJECT_NAME} --NMS_Constructor1                                     
./${PROJECT_NAME} --NMS_Constructor2                                     
./${PROJECT_NAME} --NMS_PutNeural                                        
./${PROJECT_NAME} --NMS_GetNeural                                        
./${PROJECT_NAME} --NMS_SetLearningRate1                                 
./${PROJECT_NAME} --NMS_SetLearningRate2                                 
./${PROJECT_NAME} --NMS_Error                                            
./${PROJECT_NAME} --NMS_Propagate                                        
./${PROJECT_NAME} --NMS_BackPropagate                                    
./${PROJECT_NAME} --N32_Learning                                         
./${PROJECT_NAME} --N32_Learning2                                        
./${PROJECT_NAME} --NMS_Learning                                         
./${PROJECT_NAME} --NMS_Learning2
./${PROJECT_NAME} --NMS_Pyramid                                          
./${PROJECT_NAME} --NMS_Macros1                                          
./${PROJECT_NAME} --NMS_Macros2                                          
./${PROJECT_NAME} --NMS_Genetics --GeneticFilename Genetics/Ternary.txt  
./${PROJECT_NAME} --NMS_Mutate   --GeneticFilename Genetics/Ternary.txt  
./${PROJECT_NAME} --M_NU_ConstDest                                       
./${PROJECT_NAME} --M_NU_CopyConstDest                                   
./${PROJECT_NAME} --M_NU_DimConstDest                                    
./${PROJECT_NAME} --M_NU_Rho                                             
./${PROJECT_NAME} --M_NU_Sig                                             
./${PROJECT_NAME} --M_NU_SetNext                                         
./${PROJECT_NAME} --M_NU_SetPrev                                         
./${PROJECT_NAME} --M_NU_SetInput                                        
./${PROJECT_NAME} --M_NU_GetOutput                                       
./${PROJECT_NAME} --M_NU_PutNeural                                       
./${PROJECT_NAME} --M_NU_GetNeural                                       
./${PROJECT_NAME} --M_NU_Propagate1                                      
./${PROJECT_NAME} --M_NU_Propagate2                                      
./${PROJECT_NAME} --M_NU_BackPropagate1                                  
./${PROJECT_NAME} --M_NU_BackPropagate2                                  
./${PROJECT_NAME} --M_NU_Error                                           
./${PROJECT_NAME} --M_NMS_ConstDest                                      
./${PROJECT_NAME} --M_NMS_CopyConstDest                                  
./${PROJECT_NAME} --M_NMS_DimConstDest                                   
./${PROJECT_NAME} --M_NMS_PushBack                                       
./${PROJECT_NAME} --M_NMS_SetRho1                                        
./${PROJECT_NAME} --M_NMS_SetRho2                                        
./${PROJECT_NAME} --M_NMS_SetSig1                                        
./${PROJECT_NAME} --M_NMS_SetSig2                                        
./${PROJECT_NAME} --M_NMS_PutNeural                                      
./${PROJECT_NAME} --M_NMS_Propagate                                      
./${PROJECT_NAME} --M_NMS_BackPropagate1                                 
./${PROJECT_NAME} --M_NMS_BackPropagate2                                 
./${PROJECT_NAME} --M_NMS_Error                                          
